### ISSUE TITLE
Improve Saving Performance

### ISSUE THREAD

**Issue by ajos6183** [ixmilia/threemf#1]
Hi @brettfo ,

Thank you for the library. Just wanted to let you know that for the file that i was working with, the saving operation could be sped up by a factor of 40 by removing the `IndexOf` call on the list of vertices:

In `ThreeMfTriangle.cs`, replace:

      internal XElement ToXElement(List<ThreeMfVertex> vertices, Dictionary<ThreeMfResource, int> resourceMap)
        {
            return new XElement(TriangleName,
                new XAttribute(V1AttributeName, GetVertexIndex(vertices, V1)),
                new XAttribute(V2AttributeName, GetVertexIndex(vertices, V2)),
                new XAttribute(V3AttributeName, GetVertexIndex(vertices, V3)),
                PropertyResource == null
                    ? null
                    : new[]
                    {
                        new XAttribute(PropertyIndexAttributeName, resourceMap[(ThreeMfResource)PropertyResource]),
                        V1PropertyIndex == null ? null : new XAttribute(V1PropertyAttributeName, V1PropertyIndex.GetValueOrDefault()),
                        V2PropertyIndex == null ? null : new XAttribute(V2PropertyAttributeName, V2PropertyIndex.GetValueOrDefault()),
                        V3PropertyIndex == null ? null : new XAttribute(V3PropertyAttributeName, V3PropertyIndex.GetValueOrDefault())
                    });
        }

        private static int GetVertexIndex(List<ThreeMfVertex> vertices, ThreeMfVertex item)
        {
            return vertices.IndexOf(item);
        }

with

      internal XElement ToXElement(Dictionary<ThreeMfVertex, int> vertices, Dictionary<ThreeMfResource, int> resourceMap)
      {
         return new XElement(TriangleName,
             new XAttribute(V1AttributeName, vertices[V1]),
             new XAttribute(V2AttributeName, vertices[V2]),
             new XAttribute(V3AttributeName, vertices[V3]),
             PropertyResource == null
                 ? null
                 : new[]
                 {
                        new XAttribute(PropertyIndexAttributeName, resourceMap[(ThreeMfResource)PropertyResource]),
                        V1PropertyIndex == null ? null : new XAttribute(V1PropertyAttributeName, V1PropertyIndex.GetValueOrDefault()),
                        V2PropertyIndex == null ? null : new XAttribute(V2PropertyAttributeName, V2PropertyIndex.GetValueOrDefault()),
                        V3PropertyIndex == null ? null : new XAttribute(V3PropertyAttributeName, V3PropertyIndex.GetValueOrDefault())
                 });
      }

and in `ThreeMfMesh.cs`, replace:

        internal XElement ToXElement(Dictionary<ThreeMfResource, int> resourceMap)
        {
         var vertices = Triangles.SelectMany(t => new[] { t.V1, t.V2, t.V3 }).Distinct().ToList();
            var verticesXml = vertices.Select(v => v.ToXElement());
            var trianglesXml = Triangles.Select(t => t.ToXElement(vertices, resourceMap));
            return new XElement(ThreeMfObject.MeshName,
                new XElement(VerticesName, verticesXml),
                new XElement(TrianglesName, trianglesXml));
        }

with 

        internal XElement ToXElement(Dictionary<ThreeMfResource, int> resourceMap)
        {
         var vertices = Triangles.SelectMany(t => new[] { t.V1, t.V2, t.V3 }).Distinct().Select((s, i) => new { s, i }).ToDictionary(x => x.s, x => x.i);
         var verticesXml = vertices.Select(v => v.Key.ToXElement());
            var trianglesXml = Triangles.Select(t => t.ToXElement(vertices, resourceMap));
            return new XElement(ThreeMfObject.MeshName,
                new XElement(VerticesName, verticesXml),
                new XElement(TrianglesName, trianglesXml));
        }

**Comment by brettfo** [comment]
Thank you, this is fantastic!

I'd like for you to get the appropriate credit for this fix.  You can either (1) send a PR that I'll merge or (2) I can create the commit with your info as the author.  If you want to go with option 2, what name/email would you like associated with the change?

**Comment by ajos6183** [comment]
Glad to contribute something! It would be good if you can create the commit but no need to mention me. Thanks again for your work. It saved me from having to follow this [approach](https://blogs.windows.com/windowsdeveloper/2017/01/25/calling-windows-10-apis-desktop-application/).

**Comment by brettfo** [comment]
Thanks again, pushed a commit with your fix.
